// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Action struct {
	ID              string             `json:"id"`
	Name            *string            `json:"name"`
	InternshipModel []*InternshipModel `json:"internshipModel"`
}

type Internship struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	Masters         []*User          `json:"masters"`
	InternshipModel *InternshipModel `json:"internshipModel"`
	Students        []*User          `json:"students"`
}

type InternshipModel struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Actions []*Action `json:"actions"`
}

type Log struct {
	ID      string    `json:"id"`
	Student *User     `json:"student"`
	Action  *Action   `json:"action"`
	Master  *User     `json:"master"`
	Date    time.Time `json:"date"`
}

type NewAction struct {
	Name string `json:"name"`
}

type User struct {
	ID         string        `json:"id"`
	Number     string        `json:"number"`
	NCode      *string       `json:"nCode"`
	Username   string        `json:"username"`
	Password   string        `json:"password"`
	Name       *string       `json:"name"`
	Lastname   *string       `json:"lastname"`
	Role       string        `json:"Role"`
	Phone      *string       `json:"phone"`
	Internship []*Internship `json:"internship"`
}
