// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Action struct {
	ID              string             `json:"id"`
	Name            *string            `json:"name"`
	InternshipModel []*InternshipModel `json:"internshipModel" gorm:"many2many:internship_model_action"`
	UpdateAt        string             ``
}

type Internship struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	InternshipModel *InternshipModel `json:"internshipModel"`
	Users           []*User          `json:"users" gorm:"many2many:user_internship"`
	UpdateAt        string           ``
}

type InternshipModel struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Actions  []*Action `json:"actions" gorm:"many2many:internship_model_action"`
	UpdateAt string    ``
}

type Log struct {
	ID       string    `json:"id"`
	Student  *User     `json:"student"`
	Action   *Action   `json:"action"`
	Master   *User     `json:"master"`
	Date     time.Time `json:"date"`
	UpdateAt string    ``
}

type NewAction struct {
	Name     string `json:"name"`
	UpdateAt string ``
}

type User struct {
	ID         string        `json:"id"`
	Number     string        `json:"number"`
	NCode      *string       `json:"nCode"`
	Username   string        `json:"username"`
	Password   string        `json:"password"`
	Name       *string       `json:"name"`
	Lastname   *string       `json:"lastname"`
	Role       string        `json:"Role"`
	Phone      *string       `json:"phone"`
	Internship []*Internship `json:"internship" gorm:"many2many:user_internship"`
	UpdateAt   string        ``
}
